dist: xenial

#saying install python 3.7 on the server and then install and call pytest

language: python
python:
  - "3.7"
install:
  - pip install pytest
script:
  - pytest

  #specifying that travis should run pytest command on the server